yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
packageExtensions:
  "@storybook/addon-knobs@*":
    peerDependencies:
      react-dom: "^16.14.0"
  "@storybook/addon-links@*":
    peerDependencies:
      react-dom: "^16.14.0"
  "@storybook/api@*":
    peerDependencies:
      react-dom: "^16.14.0"
  "@storybook/addon-info@*":
    peerDependencies:
      react-dom: "^16.14.0"
  "@apollo/react-hoc@*":
    peerDependencies:
      apollo-utilities: "*"
      apollo-link: "*"
      apollo-cache: "*"
